export {default as Home} from './Home/Home'
export {default as NewArticle} from './NewArticle/NewArticle'
export {default as Setting} from './settingPage/Setting'
export {default as UserInfo} from './userInfo/UserInfo'
export {default as Details} from './DetailsPage/Details'